### ISSUE TITLE
⚠ WARN: Unreachables

### ISSUE THREAD

**Issue by djrrb** [djrrb/ForeverForma#3]
⚠ WARN: Check font contains no unreachable glyphs ([com.google.fonts/check/unreachable_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs))
* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules: - cent.tf.rvrn - dollar.tf.rvrn - cent.rvrn - And dollar.rvrn [code: unreachable-glyphs]
* 

I think this is okay since I want the glyphs in for the variable font and they are being swapped. But if you have ideas on how to be clever about removing them, I am all ears.

**Comment by glenda-tn** [comment]
If these are only needed for the variable font, could you set it to not export just in the statics? like create a filter for the statics and one for the VF?
