### ISSUE TITLE
⚠ WARN: Mac Names

### ISSUE THREAD

**Issue by djrrb** [djrrb/ForeverForma#4]
⚠ WARN: Check if font has Mac name table entries (platform=1) (derived from [com.fontwerk/check/no_mac_entries](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/%3CSection:%20Fontwerk%3E.html#com.fontwerk/check/no_mac_entries)) (com.fontwerk/check/no_mac_entries)

Glyphs files have Export Mac names unchecked. I’m inclined to leave it.

**Comment by glenda-tn** [comment]
Yeah, it is weird that the parameter is keeping Name IDs 256 and up. 🤷🏽‍♀️
