### ISSUE TITLE
🔥 FAIL: Checking if STAT entries matches fvar and vice versa. (VF Italic Only)

### ISSUE THREAD

**Issue by djrrb** [djrrb/ForeverForma#6]
🔥 FAIL: Checking if STAT entries matches fvar and vice versa. ([com.fontwerk/check/inconsistencies_between_fvar_stat](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/%3CSection:%20Fontwerk%3E.html#com.fontwerk/check/inconsistencies_between_fvar_stat))
- 🔥 **FAIL** Body Text Light Italic: 'wght' axis value '300.0' missing in STAT table. [code: missing-fvar-instance-axis-value
- 🔥 **FAIL** Body Text Italic: 'wght' axis value '400.0' missing in STAT table. [code: missing-fvar-instance-axis-value] 
- 🔥 **FAIL** Body Text Medium Italic: 'wght' axis value '500.0' missing in STAT table. [code: missing-fvar-instance-axis-value]
- 🔥 **FAIL** Body Text Bold Italic: 'wght' axis value '700.0' missing in STAT table. [code: missing-fvar-instance-axis-value]

Not sure how to set this in Glyphs.

**Comment by guidoferreyra** [comment]
By adding the following parameter to the instances, is possible that the STAT Axis Values get correct values.

![imagen](https://user-images.githubusercontent.com/1755590/201223943-e5508a47-c6f7-402e-a0e6-7fa8f288f74a.png)
