### ISSUE TITLE
Outline Correctness Checks

### ISSUE THREAD

**Issue by glenda-tn** [djrrb/ForeverForma#7]
**ForeverFormaBodyText-Regular.ttf**
⚠️ WARN
The following glyphs have jaggy segments:

* ampersand (U+0026): B<<363.0,332.0>-<400.0,291.0>-<398.0,294.0>>/L<<398.0,294.0>--<498.0,183.0>> = 8.325650330426848
<img width="347" alt="Screen Shot 2022-11-10 at 12 10 37 PM" src="https://user-images.githubusercontent.com/93950887/201196182-28922b3b-96ff-44b1-b0c6-a1f0419f8cf5.png">
<img width="302" alt="Screen Shot 2022-11-10 at 12 10 53 PM" src="https://user-images.githubusercontent.com/93950887/201196207-49011802-0efe-4bbb-b624-3db51f38c2d1.png">

**ForeverFormaBodyText-LightItalic.ttf**
⚠️ WARN
The following glyphs have jaggy segments:

* partialdiff (U+2202): B<<440.5,389.5>-<467.0,355.0>-<472.0,311.0>>/B<<472.0,311.0>-<476.0,349.0>-<476.0,366.0>>
<img width="343" alt="Screen Shot 2022-11-10 at 12 21 10 PM" src="https://user-images.githubusercontent.com/93950887/201198118-546b0060-da9a-4e94-8cd0-bf481365492b.png">

<img width="301" alt="Screen Shot 2022-11-10 at 12 20 50 PM" src="https://user-images.githubusercontent.com/93950887/201198114-0d6b679d-0798-436c-8550-a6d961ea2db8.png">

**ForeverFormaBodyText-Light.ttf**
⚠️ WARN
The following glyphs have jaggy segments:

* eth (U+00F0): B<<395.0,421.0>-<444.0,380.0>-<458.0,325.0>>/B<<458.0,325.0>-<455.0,398.0>-<427.5,460.0>> = 11.927798869862459 

I couldn't really see the jagginess in this one but there is a square point in the same location as the partialdiff so if you enlarge like 10k times maybe it'll be seen. 🔍 

There are reports of **misaligned on-curve points**. Many are close to the alignment zones. This plug-in, [Show Nodes Close to Zones](https://github.com/moontypespace/NodesCloseToZones-Glyphs), by Olli Meier is useful. It can be added via the Glyphs Plug-In Manager. It gives a visual overview so you can see right away if anything needs adjustments.

**Comment by djrrb** [comment]
This is a postprocess TTF conversion issue. I removed some of the tension from the ampersand but am inclined to leave the rest as-is since I cannot edit them directly in the sources.
