### ISSUE TITLE
check kerning, mk2base positioning

### ISSUE THREAD

**Issue by glenda-tn** [djrrb/ForeverForma#9]
I'm not sure what the language coverage requirement is for this but I just ran a few strings in the index.html from the fontQA webproof. I collected some of these from https://bulletproof.italic.space/gotchas and have been using them when proofing. Apparently the caron glyphs are often [used in Czech word endings.](https://forum.glyphsapp.com/t/vertical-caron-kerning-pairs/16604/6)

The 2nd is string for Navajo, except the double Idieresis. Forever Forma doesn't support Cyrillic but it's cool to know that _ÏÏ_ is the Ukrainian word for “her.”

> The possible collision of dieresis in Ukrainian word її (‘her’) can be avoided by providing a ligature with three dots instead of four.

The third string is for Marshallese, but to really get the cedillas under the L and N properly, one needs a zerowidthnonjoiner.

```
ď. ď, ď: ď; ď- ď? ď! ť. ť, ť; ť: ť- ť? ť! ď” ľ” ť” ď“ ľ“ ť“
Ą ą Ą́ ą́ Ę ę Ę́ ę́ Į į Į́ į Ǫ ǫ Ǫ́ ǫ́  Į́ į´  ÏÏ  ïï
katļo̧k ļaņtōn m̧ajeļ ĻAŅTŌN M̧AJEĻ
```
![Screen Shot 2022-11-10 at 1 05 56 PM](https://user-images.githubusercontent.com/93950887/201208609-d3aa0292-daac-4aff-85ab-8975b6d2d76e.png)
![Screen Shot 2022-11-10 at 1 10 15 PM](https://user-images.githubusercontent.com/93950887/201208633-683617cb-6daa-4a1e-81d3-ab87237fe1e9.png)

**Comment by djrrb** [comment]
I’ve tweaked the caron kerning and added an anchor for ogonek to O and o. I don’t think it makes sense to invest much more time in language support for this custom job. Most of these characters are going to be subset out of the fonts they use.
